# font_family      family="JetBrainsMono Nerd Font Mono"
font_family      family="UbuntuMono Nerd Font Mono"

bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0
modify_font cell_height 2px

# niri manages the transparency settings, so I comment this out here
# background_opacity 0.8

# Dynamically include current theme (managed by scripts/switch-theme.sh)
include ./current-theme.conf

# Tab bar appearance
tab_bar_style separator
tab_separator " │ "
tab_bar_edge top
tab_bar_align left
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_title_max_length 32
tab_title_template "{sup.index} {title}"
active_tab_title_template "{sup.index} {title} · {tab.active_exe}"

# Keybindings
# map shift+ctrl+return new_tab
# map shift+ctrl+n new_tab
# map shift+ctrl+h previous_tab
# map shift+ctrl+l next_tab

# Enable remote control
allow_remote_control yes

shell_integration no-cursor

# disable window decorations to avoid conflicts with niri
hide_window_decorations yes
